<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="kb_messageSet" targetNamespace="http://tempuri.org/kb_messageSet" xmlns:oldtns1="http://www.mrmnames.net" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://tempuri.org/kb_messageSet" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <binding hasEncoding="false" imported="true" name="kb_messageSetSOAP_HTTP_Binding" originalBindingStyle="document"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
  <wsdl:types>
    <xsd:schema targetNamespace="http://tempuri.org/kb_messageSet" xmlns:mrm="http://tempuri.org/kb_messageSet">
<xsd:import namespace="http://www.mrmnames.net" schemaLocation="net/mrmnames/www/KB_messageDefinition.xsd"/>
</xsd:schema>
  </wsdl:types>
  <wsdl:message name="Operation1_in">
    <wsdl:part element="oldtns1:inputMsg" name="inputMsg"/>
  </wsdl:message>
  <wsdl:message name="Operation1_out">
    <wsdl:part element="oldtns1:outputMsg" name="outputMsg"/>
  </wsdl:message>
  <wsdl:message name="Operation1_fault1">
    <wsdl:part element="oldtns1:errorMsg" name="errorMsg"/>
  </wsdl:message>
  <wsdl:portType name="kb_messageSetPortType">
    <wsdl:operation name="Operation1">
      <wsdl:input message="tns:Operation1_in" name="Operation1_Input"/>
      <wsdl:output message="tns:Operation1_out" name="Operation1_Output"/>
      <wsdl:fault message="tns:Operation1_fault1" name="Operation1_Fault"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="kb_messageSetSOAP_HTTP_Binding" type="tns:kb_messageSetPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="Operation1">
      <soap:operation soapAction=""/>
      <wsdl:input name="Operation1_Input">
        <soap:body parts="inputMsg" use="literal"/>
      </wsdl:input>
      <wsdl:output name="Operation1_Output">
        <soap:body parts="outputMsg" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="Operation1_Fault">
        <soap:fault name="Operation1_Fault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="kb_messageSetSOAP_HTTP_Service">
    <wsdl:port binding="tns:kb_messageSetSOAP_HTTP_Binding" name="kb_messageSetSOAP_HTTP_Port">
      <soap:address location="http://localhost:7800/kb_messageSetSOAP_HTTP_Service"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>